-- ================================================================
-- IIDX Arena King / Supabase初期構築・更新SQL
-- 既存環境でも再実行できるよう、追加列はALTER TABLEで安全に追加します。
-- ================================================================

create table if not exists public.tournaments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  event_date date,
  created_at timestamptz not null default now()
);

-- 抽選表は大会ごとにJSONで保存し、過去大会の組み合わせも閲覧できるようにします。
alter table public.tournaments add column if not exists draw_schedule jsonb not null default '[]'::jsonb;
alter table public.tournaments add column if not exists called_match_number integer;
-- 過去回として作成した大会を、作成順に依存せず明示的に判定するための列です。
alter table public.tournaments add column if not exists is_archived boolean not null default false;

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 30),
  title text not null default '' check (char_length(title) <= 80),
  image_url text not null default '',
  created_at timestamptz not null default now(),
  unique (tournament_id, name)
);

-- 既存大会の参加者にも二つ名と選手画像を後から登録できるようにします。
alter table public.participants add column if not exists title text not null default '';
alter table public.participants add column if not exists image_url text not null default '';

-- 選手画像は公開バケットへ保存し、書き込み・削除はログイン済み運営者だけに限定します。
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('player-images','player-images',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "player_images_operator_insert" on storage.objects;
drop policy if exists "player_images_operator_delete" on storage.objects;
create policy "player_images_operator_insert" on storage.objects
  for insert to authenticated with check (bucket_id='player-images');
create policy "player_images_operator_delete" on storage.objects
  for delete to authenticated using (bucket_id='player-images');

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  stage text not null check (stage in ('preliminary', 'king', 'middle', 'reverse')),
  round_number integer not null check (round_number > 0),
  created_at timestamptz not null default now(),
  unique (tournament_id, stage, round_number)
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  participant_id bigint not null references public.participants(id) on delete restrict,
  points integer not null check (points >= 0),
  placement integer not null check (placement between 1 and 4),
  selected_chart text not null default '',
  unique (match_id, participant_id)
);

-- アリーナでは同率順位が発生するため、1試合内の順位は重複を許可します。
-- 旧スキーマで自動生成された一意制約も、再実行時に安全に解除します。
alter table public.results drop constraint if exists results_match_id_placement_key;

-- 大文字小文字と前後空白を無視し、自身が同じ譜面を再選曲することを禁止します。
create unique index if not exists results_participant_chart_unique
  on public.results (participant_id, lower(trim(selected_chart))) where trim(selected_chart) <> '';

/** 1大会の参加者を12名までに制限します。 */
create or replace function public.enforce_participant_limit() returns trigger
language plpgsql set search_path = public as $$
begin
  if (select count(*) from public.participants where tournament_id = new.tournament_id) >= 12 then
    raise exception '参加者は12名までです。';
  end if;
  return new;
end; $$;
drop trigger if exists participants_limit_trigger on public.participants;
create trigger participants_limit_trigger before insert on public.participants
for each row execute function public.enforce_participant_limit();

alter table public.tournaments enable row level security;
alter table public.participants enable row level security;
alter table public.matches enable row level security;
alter table public.results enable row level security;

drop policy if exists "tournaments_public_read" on public.tournaments;
drop policy if exists "tournaments_operator_write" on public.tournaments;
drop policy if exists "participants_public_read" on public.participants;
drop policy if exists "participants_operator_write" on public.participants;
drop policy if exists "matches_public_read" on public.matches;
drop policy if exists "matches_operator_write" on public.matches;
drop policy if exists "results_public_read" on public.results;
drop policy if exists "results_operator_write" on public.results;

-- 順位、抽選表、呼び出し状態は観戦者にも公開し、更新はログイン済み運営者に限定します。
create policy "tournaments_public_read" on public.tournaments for select to anon, authenticated using (true);
create policy "participants_public_read" on public.participants for select to anon, authenticated using (true);
create policy "matches_public_read" on public.matches for select to anon, authenticated using (true);
create policy "results_public_read" on public.results for select to anon, authenticated using (true);
create policy "tournaments_operator_write" on public.tournaments for all to authenticated using (true) with check (true);
create policy "participants_operator_write" on public.participants for all to authenticated using (true) with check (true);
create policy "matches_operator_write" on public.matches for all to authenticated using (true) with check (true);
create policy "results_operator_write" on public.results for all to authenticated using (true) with check (true);

-- 1試合と4名分の結果を同じトランザクションで登録します。
create or replace function public.create_match_with_results(
  p_tournament_id bigint, p_stage text, p_results jsonb
) returns bigint language plpgsql security definer set search_path = public as $$
declare v_match_id bigint; v_round_number integer;
begin
  if auth.uid() is null then raise exception '運営ログインが必要です。'; end if;
  if p_stage not in ('preliminary','king','middle','reverse') then raise exception '試合区分が不正です。'; end if;
  if jsonb_array_length(p_results) <> 4 then raise exception '4人分の結果を入力してください。'; end if;
  if (select count(distinct participant_id) from jsonb_to_recordset(p_results) as x(participant_id bigint)) <> 4 then
    raise exception '異なる4名を選択してください。';
  end if;
  if exists (
    select 1 from jsonb_to_recordset(p_results) as x(placement integer)
    where placement is null or placement not between 1 and 4
  ) then
    raise exception '順位は1位から4位の範囲で指定してください。';
  end if;
  if (select count(*) from public.participants where tournament_id=p_tournament_id and id in
      (select participant_id from jsonb_to_recordset(p_results) as x(participant_id bigint))) <> 4 then
    raise exception '選択した参加者が大会に登録されていません。';
  end if;
  if p_stage='preliminary' and (select count(*) from public.matches where tournament_id=p_tournament_id and stage='preliminary') >= 18 then
    raise exception '予選は全18試合までです。';
  end if;
  if p_stage='preliminary' and exists (
    select 1 from jsonb_to_recordset(p_results) as x(participant_id bigint)
    where (select count(*) from public.results r join public.matches m on m.id=r.match_id
      where r.participant_id=x.participant_id and m.tournament_id=p_tournament_id and m.stage='preliminary') >= 6
  ) then raise exception '予選は1人6試合までです。'; end if;
  select coalesce(max(round_number),0)+1 into v_round_number from public.matches where tournament_id=p_tournament_id and stage=p_stage;
  insert into public.matches(tournament_id,stage,round_number) values(p_tournament_id,p_stage,v_round_number) returning id into v_match_id;
  insert into public.results(match_id,participant_id,points,placement,selected_chart)
    select v_match_id,participant_id,points,placement,coalesce(selected_chart,'')
    from jsonb_to_recordset(p_results) as x(participant_id bigint,points integer,placement integer,selected_chart text);
  return v_match_id;
end; $$;
revoke all on function public.create_match_with_results(bigint,text,jsonb) from public;
grant execute on function public.create_match_with_results(bigint,text,jsonb) to authenticated;
