-- ================================================================
-- IIDX Arena King: Supabase初期構築SQL
-- Supabase Dashboard > SQL Editor に貼り付けて1回実行してください。
-- ================================================================

-- 大会ごとに参加者・試合・結果を分離して、過去大会も保存できるようにします。
create table if not exists public.tournaments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  event_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 30),
  created_at timestamptz not null default now(),
  unique (tournament_id, name)
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  stage text not null check (stage in ('preliminary', 'king', 'middle', 'reverse')),
  round_number integer not null check (round_number > 0),
  created_at timestamptz not null default now(),
  unique (tournament_id, stage, round_number)
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  participant_id bigint not null references public.participants(id) on delete restrict,
  points integer not null check (points >= 0),
  placement integer not null check (placement between 1 and 4),
  selected_chart text not null default '',
  unique (match_id, participant_id),
  unique (match_id, placement)
);

-- 同じ参加者が同一譜面名を再登録できないよう、大文字小文字と前後空白を無視して一意にします。
create unique index if not exists results_participant_chart_unique
  on public.results (participant_id, lower(trim(selected_chart)))
  where trim(selected_chart) <> '';

comment on table public.tournaments is '大会名と開催日を保存する親テーブル';
comment on table public.participants is '大会ごとの参加者';
comment on table public.matches is '予選および各順位決定戦';
comment on table public.results is '試合ごとの順位、獲得ポイント、選曲譜面';

-- 1大会の参加者を12名までに制限します。画面だけでなくDB側でも大会ルールを保証します。
create or replace function public.enforce_participant_limit()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (select count(*) from public.participants where tournament_id = new.tournament_id) >= 12 then
    raise exception '参加者は12名までです。';
  end if;
  return new;
end;
$$;

drop trigger if exists participants_limit_trigger on public.participants;
create trigger participants_limit_trigger
  before insert on public.participants
  for each row execute function public.enforce_participant_limit();

-- ブラウザから直接Supabaseへ接続するため、全テーブルでRLSを有効にします。
alter table public.tournaments enable row level security;
alter table public.participants enable row level security;
alter table public.matches enable row level security;
alter table public.results enable row level security;

-- SQLを再実行できるよう、同名ポリシーがある場合はいったん削除します。
drop policy if exists "tournaments_public_read" on public.tournaments;
drop policy if exists "tournaments_operator_write" on public.tournaments;
drop policy if exists "participants_public_read" on public.participants;
drop policy if exists "participants_operator_write" on public.participants;
drop policy if exists "matches_public_read" on public.matches;
drop policy if exists "matches_operator_write" on public.matches;
drop policy if exists "results_public_read" on public.results;
drop policy if exists "results_operator_write" on public.results;

-- 順位表と試合結果はログインしていない観戦者にも公開します。
create policy "tournaments_public_read" on public.tournaments for select to anon, authenticated using (true);
create policy "participants_public_read" on public.participants for select to anon, authenticated using (true);
create policy "matches_public_read" on public.matches for select to anon, authenticated using (true);
create policy "results_public_read" on public.results for select to anon, authenticated using (true);

-- 登録・変更・削除はSupabase Authでログインした運営者だけに許可します。
create policy "tournaments_operator_write" on public.tournaments for all to authenticated using (true) with check (true);
create policy "participants_operator_write" on public.participants for all to authenticated using (true) with check (true);
create policy "matches_operator_write" on public.matches for all to authenticated using (true) with check (true);
create policy "results_operator_write" on public.results for all to authenticated using (true) with check (true);

-- 1試合と4人分の結果を同じトランザクションで登録するRPCです。
-- 途中で失敗した場合は全体がロールバックされ、不完全な試合が残りません。
create or replace function public.create_match_with_results(
  p_tournament_id bigint,
  p_stage text,
  p_results jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match_id bigint;
  v_round_number integer;
begin
  if auth.uid() is null then
    raise exception '運営ログインが必要です。';
  end if;

  if p_stage not in ('preliminary', 'king', 'middle', 'reverse') then
    raise exception '試合区分が不正です。';
  end if;

  if jsonb_array_length(p_results) <> 4 then
    raise exception '4人分の結果を入力してください。';
  end if;

  if (select count(distinct participant_id) from jsonb_to_recordset(p_results) as x(participant_id bigint, points integer, placement integer, selected_chart text)) <> 4 then
    raise exception '異なる4名を選択してください。';
  end if;

  if (select count(distinct placement) from jsonb_to_recordset(p_results) as x(participant_id bigint, points integer, placement integer, selected_chart text) where placement between 1 and 4) <> 4 then
    raise exception '順位は1位から4位を1人ずつ指定してください。';
  end if;

  if (select count(*) from public.participants where tournament_id = p_tournament_id and id in (select participant_id from jsonb_to_recordset(p_results) as x(participant_id bigint))) <> 4 then
    raise exception '選択した参加者が大会に登録されていません。';
  end if;

  -- 予選では各参加者の出場回数が6試合を超えないようにします。
  if p_stage = 'preliminary' and exists (
    select 1
      from jsonb_to_recordset(p_results) as x(participant_id bigint)
     where (
       select count(*)
         from public.results r
         join public.matches m on m.id = r.match_id
        where r.participant_id = x.participant_id
          and m.tournament_id = p_tournament_id
          and m.stage = 'preliminary'
     ) >= 6
  ) then
    raise exception '予選は1人6試合までです。';
  end if;

  select coalesce(max(round_number), 0) + 1
    into v_round_number
    from public.matches
   where tournament_id = p_tournament_id and stage = p_stage;

  insert into public.matches (tournament_id, stage, round_number)
  values (p_tournament_id, p_stage, v_round_number)
  returning id into v_match_id;

  insert into public.results (match_id, participant_id, points, placement, selected_chart)
  select v_match_id, participant_id, points, placement, coalesce(selected_chart, '')
    from jsonb_to_recordset(p_results)
      as x(participant_id bigint, points integer, placement integer, selected_chart text);

  return v_match_id;
end;
$$;

-- RPCを誰でも実行できないようにし、ログイン済みユーザーだけへ公開します。
revoke all on function public.create_match_with_results(bigint, text, jsonb) from public;
grant execute on function public.create_match_with_results(bigint, text, jsonb) to authenticated;
